name: Build and test the package
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install build dependencies
      run: |
        conda install -y -c defaults -c conda-forge conda-build conda-verify codecov flake8 pep257 yapf==0.25.0
    - name: Verify formatting compliance
      run: |
        source /usr/share/miniconda/bin/activate
        python scripts/run_tests.py --format-only
    - name: Build the package
      run: conda build conda.recipe --no-test
    - name: Reduce the size of the build artifact
      run: rm -rf /usr/share/miniconda/conda-bld/{git_cache,work,anaconda-project*,*/.cache}
    - name: Upload the build artifact
      uses: actions/upload-artifact@v2
      with:
        name: package-${{ github.sha }}
        path: /usr/share/miniconda/conda-bld
  tests:
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    needs: [package,testbed]
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest,ubuntu-latest,windows-latest]
        pyver: [3.6,3.7,3.8,2.7]
        cver: [4.6,4.7,4.8]
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@v2
    - name: Build the conda environment
      run: |
          [ "$RUNNER_OS" == "Windows" ] && CONDA_EXE="$CONDA/Scripts/conda.exe"
          [ "$RUNNER_OS" == "macOS" ] && export CONDA_PKGS_DIRS=~/.pkgs
          ${CONDA_EXE:-conda} create -y -p ./conda python=${{ matrix.pyver }} conda=${{ matrix.cver }} \
            requests ruamel_yaml 'tornado >=4.2' jinja2 coverage 'pytest<5' pytest-cov \
            redis notebook bokeh psutil keyring pip
    - name: Download the build artifact
      uses: actions/download-artifact@v2
      with:
        name: package-${{ github.sha }}
        path: ./conda/conda-bld
    - name: Install the package and run the tests
      run: |
        source ./conda/etc/profile.d/conda.sh 
        conda install -y local::anaconda-project 
        conda activate base
        python -m pytest --pyargs -v -rfe --durations=10
          --cov-config .coveragerc --cov-report term-missing --no-cov-on-fail
          --cov-fail-under=99 --cov-report html$COVERAGE_DIR # [not win]
          --cov anaconda_project anaconda_project
